apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hk-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hk-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: kustomized-helm
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
